version: "3.4"

x-environment:
  &environment
  DISCORD_TOKEN: ${DISCORD_TOKEN}
  DISCORD_BIRTHDAY_CHANNEL_ID: ${DISCORD_BIRTHDAY_CHANNEL_ID}
  ROLES_RECRUIT: ${ROLES_RECRUIT}
  ROLES_SLAM: ${ROLES_SLAM}
  ROLES_SWITCH: ${ROLES_SWITCH}
  ROLES_PLAYSTATION: ${ROLES_PLAYSTATION}
  ROLES_XBOX: ${ROLES_XBOX}
  ROLES_PC: ${ROLES_PC}
  ROLES_ROCKET_LEAGUE: ${ROLES_ROCKET_LEAGUE}
  ROLES_FORTNITE: ${ROLES_FORTNITE}
  ROLES_MINECRAFT: ${ROLES_MINECRAFT}
  ROLES_HUNT_SHOWDOWN: ${ROLES_HUNT_SHOWDOWN}
  ROLES_US_WEST: ${ROLES_US_WEST}
  ROLES_US_CENTRAL: ${ROLES_US_CENTRAL}
  ROLES_US_EAST: ${ROLES_US_EAST}
  ROLES_EU: ${ROLES_EU}
  ROLES_ASIA: ${ROLES_ASIA}
  MONGODB_HOST: ${MONGODB_HOST}
  MONGODB_USERNAME: ${MONGODB_USERNAME}
  MONGODB_PASSWORD: ${MONGODB_PASSWORD}
  MONGODB_DATABASE: ${MONGODB_DATABASE}
  DISCORD_DEBUG_SCOPE: ${DISCORD_DEBUG_SCOPE}

services:
  boni-bot:
    image: docker.aidenhaines.com/boni
    network_mode: host
    environment:
      <<: *environment
    restart: unless-stopped
